[metadata]
name = EstiSketch
version = 0.1.0-alpha
description = A lightweight 2-D floor-plan sketcher
long_description = file: README.md
long_description_content_type = text/markdown
author = Andrew
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    PyGObject
include_package_data = True

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    estisketch = EstiSketch.main:main

[options.package_data]
EstiSketch = *.json, Resources/*.json, Icons/*
