"""
Roof components for EstiSketch.

This module contains dataclasses for roof-related objects, kept separate
from the main components.py to isolate complexity and support future
expansion to complex roof types.
"""
from dataclasses import dataclass, field
from typing import List, Tuple, Dict, Optional, Any, Union

from models.roof import (
    ROOF_LINE_COLORS,
    RoofEdge,
    RoofVertex,
    RoofPlane,
    RoofFacet,
    Plane3D,
    Line3D,
    RoofEdgeType,
    EAVE,
    RIDGE,
    HIP,
    VALLEY,
    RAKE,
    TIE_IN,
    GABLE,
)


@dataclass
class RoofLine:
    """
    Represents an individual roof line segment (ridge, hip, valley, rake, eave, tie_in).
    Can be manually sketched by the user or auto-generated by the topology solver.
    """
    identifier: str = ""
    start: Tuple[float, float] = (0.0, 0.0)
    end: Tuple[float, float] = (0.0, 0.0)
    line_type: str = "ridge"  # "ridge", "hip", "valley", "rake", "eave", "tie_in"
    pitch_rise: Optional[float] = None  # Override pitch (rise in 12) if specified
    overhang: Optional[float] = None    # Override overhang (inches) for eaves
    is_auto_generated: bool = False     # True if solver created this line

    @property
    def length_in(self) -> float:
        """Length of line segment in inches (canvas units)."""
        import math
        return math.hypot(self.end[0] - self.start[0], self.end[1] - self.start[1])

    @property
    def length_ft(self) -> float:
        """Length of line segment in feet."""
        return self.length_in / 12.0


@dataclass
class Roof:
    """
    Represents a roof object bound to walls or defined by explicit sketched lines.
    
    Contains both wall-bound edges, manually sketched lines (manual_lines),
    and auto-solved topology lines (solved_lines) with 3D polygon plane data.
    """
    identifier: str = ""
    layer_id: str = ""
    
    # Wall bindings
    edges: List[RoofEdge] = field(default_factory=list)
    
    # Sketched / Manual Roof Lines
    manual_lines: List[RoofLine] = field(default_factory=list)
    
    # Solved topology lines (cleaned, snapped, and offset by the solver)
    solved_lines: List[RoofLine] = field(default_factory=list)
    
    # Basic Roof properties
    roof_type: str = "custom"  # "gable", "hip", "custom", "shed"
    pitch_rise: float = 6.0    # Default rise (e.g. 6 in 6/12)
    pitch_run: float = 12.0    # Default run (12)
    overhang: float = 12.0     # Default eave overhang in inches
    
    # Legacy / Rendered geometry lines (stored as ((x1, y1), (x2, y2)))
    ridge_lines: List[Tuple[Tuple[float, float], Tuple[float, float]]] = field(default_factory=list)
    hip_lines: List[Tuple[Tuple[float, float], Tuple[float, float]]] = field(default_factory=list)
    valley_lines: List[Tuple[Tuple[float, float], Tuple[float, float]]] = field(default_factory=list)
    rake_lines: List[Tuple[Tuple[float, float], Tuple[float, float]]] = field(default_factory=list)
    eave_lines: List[Tuple[Tuple[float, float], Tuple[float, float]]] = field(default_factory=list)
    tie_in_lines: List[Tuple[Tuple[float, float], Tuple[float, float]]] = field(default_factory=list)
    
    # Roof outline with overhang
    outline_points: List[Tuple[float, float]] = field(default_factory=list)
    
    # Extracted 3D Roof Planes for Takeoff Calculation
    # Each item is a RoofFacet or dict: {"name": str, "pitch": float, "polygon_2d": [...], "area_3d_sqft": float}
    roof_planes: List[Any] = field(default_factory=list)
    
    # Materials
    material: str = "asphalt_shingle"

